POST http://localhost:7777/add-product

{
    "name": "Webcam",
    "price": 200,
    "available": true
}

###

GET http://localhost:7777/get-product/1

###

GET http://localhost:7777/get-all-products